"""
Per-employee QR code generation + verification.

Design: each employee gets ONE QR code (printed/laminated once, or shown on
their phone), which encodes a signed token containing their employee_id.
The signature stops someone from handwriting/guessing an ID and checking in
as another employee — only a QR generated by this system will verify.

This is different from a per-session QR: it's long-lived (QR_TOKEN_VALIDITY_DAYS,
default ~1 year) since re-issuing every employee a new QR daily isn't practical.
Replay protection instead comes from geofence + one-check-in-per-day duplicate
detection (see models/attendance.py), not from token expiry.
"""
import io

import qrcode
from itsdangerous import BadSignature, URLSafeSerializer

from config import Config

_serializer = URLSafeSerializer(Config.SECRET_KEY, salt="employee-qr")


def sign_employee_token(employee_id: str) -> str:
    return _serializer.dumps({"employee_id": employee_id})


def verify_employee_token(token: str):
    """Returns employee_id if the token is authentic, else None."""
    try:
        data = _serializer.loads(token)
        return data.get("employee_id")
    except BadSignature:
        return None


def generate_qr_png_bytes(payload: str) -> bytes:
    img = qrcode.make(payload)
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    return buf.getvalue()


def generate_and_save_employee_qr(employee_id: str, output_dir) -> str:
    """Generates the employee's signed QR and saves it to static/qr/<id>.png.
    Returns the file path written."""
    token = sign_employee_token(employee_id)
    png_bytes = generate_qr_png_bytes(token)
    output_path = output_dir / f"{employee_id}.png"
    output_path.write_bytes(png_bytes)
    return str(output_path)
